import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author dolpi
 */
public class Transaksi extends javax.swing.JFrame {

    /**
     * Creates new form Transaksi
     */
    public Transaksi() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setLocationRelativeTo(this);
        NoTransaksi();
        generateDetailID();
        subtotal();
        tanggal();
        bayar();
        kembalian();
        tampil();
        tampilbarang();
        TambahBarang();
       tambahdetail();
        hapus();

   
    }
 public Connection conn;
   public void koneksi () throws SQLException {
       try
       {
           conn=null;
           Class.forName("com.mysql.cj.jdbc.Driver");
           conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/kasir","root","");
       } catch (ClassNotFoundException ex) {
           Logger.getLogger(Transaksi.class.getName()).log(Level.SEVERE,null,ex);
       }catch (SQLException e) {
           Logger.getLogger(Transaksi.class.getName()).log(Level.SEVERE,null, e);
       }catch (Exception es){
           Logger.getLogger(Transaksi.class.getName()).log(Level.SEVERE,null, es);
       }
       
     
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel12 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        pelanggan = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        pnjid = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jumlah = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        tgl = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        pid = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        nmproduk = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        harga = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        total = new javax.swing.JTextField();
        kembaliann = new javax.swing.JTextField();
        bayar = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel35 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jmlhbyr = new javax.swing.JTextField();
        detail = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jButton12 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel16.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel16.setText("Penjualan ID");

        jLabel17.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel17.setText("Pelanggan id");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel27))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel27)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pelanggan.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        pelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pelangganActionPerformed(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/e-commerce_8628924.png"))); // NOI18N
        jLabel28.setText("TRANSAKSI BELI BARANG");

        pnjid.setEnabled(false);
        pnjid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pnjidActionPerformed(evt);
            }
        });

        jLabel34.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel34.setText("Produk ID");

        jumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlahActionPerformed(evt);
            }
        });
        jumlah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jumlahKeyPressed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(51, 153, 255));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/loupe_428094.png"))); // NOI18N
        jButton6.setText("Cari");
        jButton6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        tgl.setEditable(false);

        jLabel36.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/calendar_591576.png"))); // NOI18N
        jLabel36.setText("Tanggal");

        jLabel31.setBackground(new java.awt.Color(0, 204, 204));
        jLabel31.setFont(new java.awt.Font("Monospaced", 1, 36)); // NOI18N
        jLabel31.setText("DALPAN STORE");

        jButton7.setBackground(new java.awt.Color(255, 204, 51));
        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/add_9503522.png"))); // NOI18N
        jButton7.setText("Cek");
        jButton7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        pid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pidActionPerformed(evt);
            }
        });
        pid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pidKeyPressed(evt);
            }
        });

        jLabel37.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel37.setText("Nama Produk");

        nmproduk.setEditable(false);

        jLabel38.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel38.setText("Jumlah");

        jLabel39.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel39.setText("Harga");

        harga.setEditable(false);
        harga.setEnabled(false);
        harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hargaActionPerformed(evt);
            }
        });

        jLabel40.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel40.setText("Total Rp.");

        jLabel41.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel41.setText("Kembali Rp.");

        jLabel42.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel42.setText("Uang Bayar Rp.");

        total.setEditable(false);
        total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalActionPerformed(evt);
            }
        });

        kembaliann.setEditable(false);
        kembaliann.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliannActionPerformed(evt);
            }
        });

        bayar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bayarKeyPressed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(0, 51, 255));
        jButton9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/add_9503522.png"))); // NOI18N
        jButton9.setText("Tambah Barang");
        jButton9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton11.setBackground(new java.awt.Color(255, 153, 0));
        jButton11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/payment_4915276.png"))); // NOI18N
        jButton11.setText("Bayar");
        jButton11.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton11.setEnabled(false);
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 153, 51));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/emergency-exit_4009127(1).png"))); // NOI18N
        jButton3.setText("KEMBALI");
        jButton3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel35.setFont(new java.awt.Font("Script MT Bold", 1, 14)); // NOI18N
        jLabel35.setText("Berbelanja dengan mudah dan cepat di Dalpan Store");

        jButton10.setBackground(new java.awt.Color(255, 255, 51));
        jButton10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/layer_10313138.png"))); // NOI18N
        jButton10.setText("Batal");
        jButton10.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable3.setCellSelectionEnabled(true);
        jTable3.setShowGrid(true);
        jScrollPane3.setViewportView(jTable3);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/9176210_6617.jpeg"))); // NOI18N

        jLabel43.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel43.setText("Jumlah Bayar Rp");

        jmlhbyr.setBackground(new java.awt.Color(204, 255, 255));

        detail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel18.setText("Detail ID");

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable4.setCellSelectionEnabled(true);
        jTable4.setShowGrid(true);
        jScrollPane4.setViewportView(jTable4);

        jButton12.setBackground(new java.awt.Color(255, 0, 0));
        jButton12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton12.setForeground(new java.awt.Color(255, 255, 255));
        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/transfer-money_4641418.png"))); // NOI18N
        jButton12.setText("Hapus Transaksi");
        jButton12.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(619, 619, 619)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel17))
                                .addGap(26, 26, 26))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                                .addComponent(jLabel34)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addComponent(pnjid, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel28)
                                .addGap(104, 104, 104))
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel12Layout.createSequentialGroup()
                                        .addComponent(pelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel12Layout.createSequentialGroup()
                                        .addComponent(pid, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(24, 24, 24)
                                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel12Layout.createSequentialGroup()
                                                .addComponent(nmproduk, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel12Layout.createSequentialGroup()
                                                        .addComponent(harga, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(28, 28, 28)
                                                        .addComponent(jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(jPanel12Layout.createSequentialGroup()
                                                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                            .addComponent(detail, javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                        .addGap(165, 165, 165)
                                                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGroup(jPanel12Layout.createSequentialGroup()
                                                                .addComponent(jLabel43)
                                                                .addGap(37, 37, 37)
                                                                .addComponent(jmlhbyr, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                            .addGroup(jPanel12Layout.createSequentialGroup()
                                                .addComponent(jLabel37)
                                                .addGap(58, 58, 58)
                                                .addComponent(jLabel39)
                                                .addGap(72, 72, 72)
                                                .addComponent(jLabel38))))
                                    .addGroup(jPanel12Layout.createSequentialGroup()
                                        .addGap(73, 73, 73)
                                        .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(83, 83, 83)
                                        .addComponent(jLabel36)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tgl, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 638, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1))
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel12Layout.createSequentialGroup()
                                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(300, 300, 300))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                                        .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton9)
                                        .addGap(12, 12, 12)
                                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)))
                                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel12Layout.createSequentialGroup()
                                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel41)
                                            .addComponent(jLabel42)
                                            .addComponent(jLabel40))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(kembaliann, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(bayar, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 456, Short.MAX_VALUE))
                                    .addGroup(jPanel12Layout.createSequentialGroup()
                                        .addGap(148, 148, 148)
                                        .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))))))
                .addGap(50, 50, 50))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel31)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(pnjid, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16))
                                .addGap(10, 10, 10)
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(detail, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(pelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton6)))
                                .addGap(0, 125, Short.MAX_VALUE))
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                                .addComponent(jLabel28)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jmlhbyr, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)))
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel35)
                        .addGap(167, 167, 167)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(pid, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton7)
                                .addComponent(nmproduk, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(harga, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bayar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25))
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)))
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(kembaliann, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1487, 1487, 1487))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
// Setelah menyimpan data penjualan, hitung ulang total sum
        bayar();
        tambahdetail();

    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed

try {
    // Mengambil nilai dari komponen UI lainnya
    String PenjualanID = String.valueOf(pnjid.getText());
    String PelangganID = String.valueOf(pelanggan.getText());
    // Konversi tanggal
    LocalDate currentDate = LocalDate.now();

    // Format tanggal saat ini ke dalam format yang diinginkan
    DateTimeFormatter formatterOutput = DateTimeFormatter.ofPattern("yyyy-MM-dd");
    String tanggalInput = currentDate.format(formatterOutput);

    // Memasukkan data ke dalam tabel 'penjualan' dengan pernyataan SQL
    try {
        
        koneksi();
        String sql = "INSERT INTO penjualan (PenjualanID, TanggalPenjualan, PelangganID, TotalHarga) VALUES (?, ?, ?, ?)";
        try (PreparedStatement preparedStatement = conn.prepareStatement(sql)) {
            preparedStatement.setString(1, PenjualanID);
            preparedStatement.setString(2, tanggalInput);
            preparedStatement.setString(3, PelangganID);
            preparedStatement.setString(4, total.getText()); // Menggunakan total yang sudah dihitung sebelumnya

            int res = preparedStatement.executeUpdate();
            if (res == 1) {
                NoTransaksi();
                generateDetailID();
                tampilbarang();
                kembalian();
                bayar();
                hapus();
                JOptionPane.showMessageDialog(null, "Tambah penjualan sukses!");
            }
        }
    } catch (SQLException e) {
         JOptionPane.showMessageDialog(this, "data Belum diisi semua","warnning",JOptionPane.WARNING_MESSAGE);

    }
} catch (Exception ex) {
    Logger.getLogger(Transaksi.class.getName()).log(Level.SEVERE, null, ex);
}

    }//GEN-LAST:event_jButton9ActionPerformed

    private void hargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hargaActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
 if (pid.getText().equals("") ) {
    JOptionPane.showMessageDialog(this, "Tidak boleh Kosong", "Warning", JOptionPane.WARNING_MESSAGE);
} else {
    try {
        koneksi();
        String sql = "select * from produk where ProdukID like '%" + pid.getText() + "%'";
        Statement stat = conn.createStatement();
        ResultSet res = stat.executeQuery(sql);

        if (res.next()) {
            // Produk ditemukan
            nmproduk.setText(res.getString("NamaProduk"));
            harga.setText(res.getString("Harga"));
            
            // Lanjutkan dengan operasi lain jika diperlukan
            subtotal();
            
            pid.requestFocus();
        } else {
            // Produk tidak ditemukan
            JOptionPane.showMessageDialog(this, "Produk tidak ditemukan", "Warning", JOptionPane.WARNING_MESSAGE);
        }

    } catch (Exception e) {
        // Handle the exception according to your application's requirements
//        e.printStackTrace();
    }
}

           
        
    
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        new pelanggan().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jumlahActionPerformed

    private void pnjidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pnjidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pnjidActionPerformed

    private void pelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pelangganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pelangganActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int jawab=JOptionPane.showOptionDialog(this, "Apakah Anda Yakin ", "Keluar",JOptionPane.YES_OPTION,
            JOptionPane.QUESTION_MESSAGE,null, null, EXIT_ON_CLOSE);
        if (jawab== JOptionPane.YES_OPTION) {
            new menupetugas().setVisible(true);
            dispose();

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        hapus();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void pidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pidActionPerformed

    private void jumlahKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jumlahKeyPressed
        // TODO add your handling code here:
       
       subtotal();
  
      
    
    }//GEN-LAST:event_jumlahKeyPressed

    private void bayarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bayarKeyPressed
    
        kembalian();
      
        
    }//GEN-LAST:event_bayarKeyPressed

    private void pidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pidKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_pidKeyPressed

    private void totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalActionPerformed

    private void detailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_detailActionPerformed

    private void kembaliannActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliannActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kembaliannActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        hapusdata();
    }//GEN-LAST:event_jButton12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bayar;
    private javax.swing.JTextField detail;
    private javax.swing.JTextField harga;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTextField jmlhbyr;
    private javax.swing.JTextField jumlah;
    private javax.swing.JTextField kembaliann;
    private javax.swing.JTextField nmproduk;
    private javax.swing.JTextField pelanggan;
    private javax.swing.JTextField pid;
    private javax.swing.JTextField pnjid;
    private javax.swing.JTextField tgl;
    private javax.swing.JTextField total;
    // End of variables declaration//GEN-END:variables

    private void NoTransaksi() {
try {
    koneksi();
    String sql = "select * from penjualan order by PenjualanID desc limit 1";
    Statement stat = conn.createStatement();
    ResultSet res = stat.executeQuery(sql);

    if (res.next()) {
        int lastPenjualanID = res.getInt("PenjualanID");
        int newPenjualanID = lastPenjualanID + 1;

        // Format nomor penjualan sesuai kebutuhan
        String formattedPenjualanID = String.format("%04d", newPenjualanID);

        pnjid.setText(formattedPenjualanID);
    } else {
        // Jika belum ada data di tabel, nomor penjualan dimulai dari 1
        pnjid.setText("0001");
    }
} catch (Exception e) {
    JOptionPane.showMessageDialog(null, e);
}


     
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void tanggal() {
          java.util.Date tglsekarang = new java.util.Date();
    SimpleDateFormat smpdtfmt = new SimpleDateFormat("dd MMMMMMMMM yyyy", Locale.getDefault());
    String tanggal = smpdtfmt.format(tglsekarang);
   tgl.setText(tanggal);
        // throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void tampil() {
               DefaultTableModel tbl = new DefaultTableModel();
        tbl.addColumn("PRODUK ID");
        tbl.addColumn("NAMA PRODUK");
        tbl.addColumn("HARGA");
          tbl.addColumn("STOK");
        try {
            koneksi();
            String sql = "select * from produk";
            Statement stat = conn.createStatement();
            ResultSet res = stat.executeQuery(sql);
            while (res.next()) {
              tbl.addRow(new Object[]{res.getString(1), res.getString(2), res.getString(3), res.getString(4)});

            }
            jTable3.setModel(tbl);
        } catch (SQLException e) {
            // Menangani eksepsi dengan mencetak pesan kesalahan
           
        }
//throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void subtotal() {
 try {
    // Ambil harga dari database berdasarkan produk yang dipilih
    String sql = "SELECT harga FROM produk WHERE ProdukID = ?";
    
    try (PreparedStatement preparedStatement = conn.prepareStatement(sql)) {
        preparedStatement.setString(1, pid.getText()); // Menggunakan ProdukID dari inputan pengguna

        try (ResultSet resultSet = preparedStatement.executeQuery()) {
            if (resultSet.next()) {
                // Retrieve the value from the result set
                BigDecimal hargaProduk = resultSet.getBigDecimal("harga");

                if (hargaProduk != null) {
                    // Continue with your logic here
                    int jumlahProduk = Integer.parseInt(jumlah.getText());

                    // Hitung total harga
                    BigDecimal totalHarga = hargaProduk.multiply(new BigDecimal(jumlahProduk));

                    // Format total harga to have at least two digits
                    String formattedTotal = String.format("%02d", totalHarga.intValue());

                    // Set nilai total harga ke dalam JTextField total
                    total.setText(formattedTotal);

                    // Simpan ke dalam database jika diperlukan
                    // ...
                }
            } else {
                // Produk tidak ditemukan
                // Tampilkan pesan kesalahan atau lakukan yang sesuai
               // JOptionPane.showMessageDialog(null, "Produk tidak ditemukan!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }
} catch (SQLException | NumberFormatException e) {
    // Handle the exception according to your application's requirements
    // JOptionPane.showMessageDialog(null, "Data harus diisi " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    // e.printStackTrace();
}



}
    private void hapus() {
       pid.setText("");
        nmproduk.setText("");
         harga.setText("");
          jumlah.setText("");
          total.setText("");
          bayar.setText("");
          kembaliann.setText("");
           pid.requestFocus();
           
// throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }


    private void tampilbarang() {
           DefaultTableModel tbl = new DefaultTableModel();
             tbl.addColumn("PenjualanID");
        tbl.addColumn("TanggalPenjualan");
       tbl.addColumn(" TotalHarga");
        tbl.addColumn("PelangganID");
      try {
         koneksi();
         String sql = "select * from penjualan";       
         Statement stat = conn.createStatement();
            ResultSet res = stat.executeQuery(sql);
           while (res.next()) {
              tbl.addRow(new Object[]{res.getString(1), res.getString(2), res.getString(3), res.getString(4)});
          }
       jTable4.setModel(tbl);
      } catch (SQLException e){ }
    }

    private void TambahBarang() {

// ...


// Menghitung total dari penjualan yang ada di database
try {
    koneksi();
    String sqlTotal = "SELECT SUM(TotalHarga) AS TotalPenjualan FROM penjualan ";
    try (PreparedStatement preparedStatementTotal = conn.prepareStatement(sqlTotal)) {
      

        try (ResultSet resultSetTotal = preparedStatementTotal.executeQuery()) {
            if (resultSetTotal.next()) {
                // Mendapatkan nilai total dari hasil query
                int totalPenjualan = resultSetTotal.getInt("TotalPenjualan");

                // Menggunakan DecimalFormat untuk menambahkan titik sebagai pemisah ribuan
                DecimalFormat decimalFormat = new DecimalFormat("#,###");
                String formattedTotal = decimalFormat.format(totalPenjualan);

                // Menampilkan nilai total yang sudah diformat di JTextField
                jmlhbyr.setText(formattedTotal);
                tampilbarang();
            }
        }
    }
} catch (SQLException e) {
   JOptionPane.showMessageDialog(this, "data Belum diisi semua","warnning",JOptionPane.WARNING_MESSAGE);
}




    }

    private void bayar() {    
     try {
        koneksi();     
        String sql="update produk set Stok=Stok - '"+jumlah.getText()+"' where ProdukID=" + "('"+ pid.getText() +"')";
        Statement stat=conn.createStatement();
        stat.executeUpdate(sql);
         tampil();
         hapus();
        stat.close();
        conn.close();
        
        } catch (Exception e){
        JOptionPane.showMessageDialog(null, "Penjualan Gagal");
        System.out.println(e.getMessage());
        }   

}
    
private String generateDetailID() {
  try {
    koneksi();
    String sql = "SELECT MAX(DetailID) FROM detailpenjualan";
    try (Statement statement = conn.createStatement();
         ResultSet resultSet = statement.executeQuery(sql)) {
        if (resultSet.next()) {
            // Mendapatkan nilai maksimum dari kolom DetailID
            int maxDetailID = resultSet.getInt(1);

            // Membuat DetailID baru dengan menambah 1 dari nilai maksimum
            int newDetailID = maxDetailID + 1;

            // Format DetailID sesuai kebutuhan
            String formattedDetailID = String.format("%04d", newDetailID);

            // Memanggil metode generateDetailID dan mengatur hasilnya ke JTextField
            detail.setText(formattedDetailID);

            // Mengembalikan nilai DetailID yang baru
            return formattedDetailID;
        }
    }
} catch (SQLException e) {
//    e.printStackTrace();
}
// Mengembalikan null jika terjadi kesalahan
return null;
}

    private void kembalian() {
// Assuming this is inside an event handler method
// Assuming this is inside an event handler method
try {
    // Menghitung total penjualan dari database
    koneksi(); // Pastikan method koneksi() sesuai dengan implementasi Anda
    String sqlTotal = "SELECT SUM(TotalHarga) AS TotalPenjualan FROM penjualan";
    
    try (PreparedStatement preparedStatementTotal = conn.prepareStatement(sqlTotal)) {
        try (ResultSet resultSetTotal = preparedStatementTotal.executeQuery()) {
            if (resultSetTotal.next()) {
                // Mendapatkan nilai total penjualan dari hasil query
                BigDecimal totalPenjualan = resultSetTotal.getBigDecimal("TotalPenjualan");

                // Set nilai total bayar sesuai dengan total penjualan
                if (totalPenjualan != null) {
                    jmlhbyr.setText(totalPenjualan.toString());
                } else {
                    jmlhbyr.setText("0"); // Set a default value or handle it according to your logic
                }

                // Tampilkan kembalian di JTextField kembaliann (optional)
                BigDecimal bayarValue = new BigDecimal(bayar.getText());
                BigDecimal kembalian = bayarValue.subtract(totalPenjualan);
                kembalian = kembalian.max(BigDecimal.ZERO);
                kembaliann.setText(kembalian.toString());

                // Simpan ke dalam database jika diperlukan
                // ...
            }
        }
    }
} catch (SQLException | NumberFormatException e) {
    // Handle the exception according to your application's requirements
//    e.printStackTrace();
}


//throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void tambahdetail() {
         String DetailID = String.valueOf(detail.getText());
     String PenjualanID = String.valueOf(pnjid.getText());
    
        String ProdukID = String.valueOf(pid.getText());
        String JumlahProduk = String.valueOf(jumlah.getText());
        String Subtotal = String.valueOf(jmlhbyr.getText());
               
        try {
        koneksi();
        String sql="insert into detailpenjualan values" + "('"+ DetailID + "','"+ PenjualanID +"','"+ ProdukID +"','"+ JumlahProduk +"','"+ Subtotal +"')";
        Statement stat=conn.createStatement();
        int res=stat.executeUpdate(sql);
        if(res==1){
            javax.swing.JOptionPane.showMessageDialog(null, "Tambah penjualan sukses!");
        }
        } catch (Exception e){
       }
//        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void hapusdata() {
    try {
    koneksi();

    // Assuming your DELETE statement deletes all records from the 'penjualan' table
    String sql = "DELETE FROM penjualan";

    // Display confirmation dialog
    int jawab = JOptionPane.showOptionDialog(
        this,
        "Apakah anda yakin ingin menghapus semua Transaksi?",
        "Konfirmasi",
        JOptionPane.YES_NO_OPTION,
        JOptionPane.QUESTION_MESSAGE,
        null,
        null,
        null
    );

    if (jawab == JOptionPane.YES_OPTION) {
        try (Statement stat = conn.createStatement()) {
            // Execute the DELETE statement
            int res = stat.executeUpdate(sql);

            if (res > 0) {
                JOptionPane.showMessageDialog(null, "Hapus data sukses!");
                
                tampilbarang();
                hapus();
                jmlhbyr.setText("0");
            } else {
                JOptionPane.showMessageDialog(null, "Tidak ada data yang dihapus.");
            }
        }
    } else {
        JOptionPane.showMessageDialog(null, "Penghapusan data dibatalkan.");
    }

    // Close the connection
    conn.close();
} catch (Exception e) {
    // Handle exceptions as needed
    // JOptionPane.showMessageDialog(null, "Gagal menghapus data: " + e.getMessage());
    // e.printStackTrace();
}

//throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
